# limits taken from # limits: https://projectcontour.io/docs/1.30/deploy-options/
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: contour
  name: contour
  namespace: projectcontour
spec:
  template:
    spec:
      containers:
        - name: contour
          $patch: merge
          resources:
            limits:
              cpu: 250m
              memory: 128Mi
---
# limits: https://projectcontour.io/docs/1.30/deploy-options/
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: envoy
  namespace: projectcontour
spec:
  template:
    spec:
      containers:
        - name: envoy
          $patch: merge
          resources:
            limits:
              cpu: 25m
              memory: 50Mi
        - name: shutdown-manager
          $patch: merge
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
